// Generated by gencpp from file srv_cli/AddInts.msg
// DO NOT EDIT!


#ifndef SRV_CLI_MESSAGE_ADDINTS_H
#define SRV_CLI_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <srv_cli/AddIntsRequest.h>
#include <srv_cli/AddIntsResponse.h>


namespace srv_cli
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace srv_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_cli::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::srv_cli::AddInts&) { return value(); }
};

template<>
struct DataType< ::srv_cli::AddInts > {
  static const char* value()
  {
    return "srv_cli/AddInts";
  }

  static const char* value(const ::srv_cli::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::srv_cli::AddIntsRequest> should match
// service_traits::MD5Sum< ::srv_cli::AddInts >
template<>
struct MD5Sum< ::srv_cli::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_cli::AddInts >::value();
  }
  static const char* value(const ::srv_cli::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_cli::AddIntsRequest> should match
// service_traits::DataType< ::srv_cli::AddInts >
template<>
struct DataType< ::srv_cli::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_cli::AddInts >::value();
  }
  static const char* value(const ::srv_cli::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_cli::AddIntsResponse> should match
// service_traits::MD5Sum< ::srv_cli::AddInts >
template<>
struct MD5Sum< ::srv_cli::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_cli::AddInts >::value();
  }
  static const char* value(const ::srv_cli::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_cli::AddIntsResponse> should match
// service_traits::DataType< ::srv_cli::AddInts >
template<>
struct DataType< ::srv_cli::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_cli::AddInts >::value();
  }
  static const char* value(const ::srv_cli::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_CLI_MESSAGE_ADDINTS_H
