// Generated by gencpp from file srv_cli/Ops.msg
// DO NOT EDIT!


#ifndef SRV_CLI_MESSAGE_OPS_H
#define SRV_CLI_MESSAGE_OPS_H

#include <ros/service_traits.h>


#include <srv_cli/OpsRequest.h>
#include <srv_cli/OpsResponse.h>


namespace srv_cli
{

struct Ops
{

typedef OpsRequest Request;
typedef OpsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Ops
} // namespace srv_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_cli::Ops > {
  static const char* value()
  {
    return "debbba91dbbcfc26ea53ae9e87ba85d6";
  }

  static const char* value(const ::srv_cli::Ops&) { return value(); }
};

template<>
struct DataType< ::srv_cli::Ops > {
  static const char* value()
  {
    return "srv_cli/Ops";
  }

  static const char* value(const ::srv_cli::Ops&) { return value(); }
};


// service_traits::MD5Sum< ::srv_cli::OpsRequest> should match
// service_traits::MD5Sum< ::srv_cli::Ops >
template<>
struct MD5Sum< ::srv_cli::OpsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_cli::Ops >::value();
  }
  static const char* value(const ::srv_cli::OpsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_cli::OpsRequest> should match
// service_traits::DataType< ::srv_cli::Ops >
template<>
struct DataType< ::srv_cli::OpsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_cli::Ops >::value();
  }
  static const char* value(const ::srv_cli::OpsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_cli::OpsResponse> should match
// service_traits::MD5Sum< ::srv_cli::Ops >
template<>
struct MD5Sum< ::srv_cli::OpsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_cli::Ops >::value();
  }
  static const char* value(const ::srv_cli::OpsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_cli::OpsResponse> should match
// service_traits::DataType< ::srv_cli::Ops >
template<>
struct DataType< ::srv_cli::OpsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_cli::Ops >::value();
  }
  static const char* value(const ::srv_cli::OpsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_CLI_MESSAGE_OPS_H
