// Generated by gencpp from file srv_cli/ops.msg
// DO NOT EDIT!


#ifndef SRV_CLI_MESSAGE_OPS_H
#define SRV_CLI_MESSAGE_OPS_H

#include <ros/service_traits.h>


#include <srv_cli/opsRequest.h>
#include <srv_cli/opsResponse.h>


namespace srv_cli
{

struct ops
{

typedef opsRequest Request;
typedef opsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ops
} // namespace srv_cli


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_cli::ops > {
  static const char* value()
  {
    return "debbba91dbbcfc26ea53ae9e87ba85d6";
  }

  static const char* value(const ::srv_cli::ops&) { return value(); }
};

template<>
struct DataType< ::srv_cli::ops > {
  static const char* value()
  {
    return "srv_cli/ops";
  }

  static const char* value(const ::srv_cli::ops&) { return value(); }
};


// service_traits::MD5Sum< ::srv_cli::opsRequest> should match
// service_traits::MD5Sum< ::srv_cli::ops >
template<>
struct MD5Sum< ::srv_cli::opsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_cli::ops >::value();
  }
  static const char* value(const ::srv_cli::opsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_cli::opsRequest> should match
// service_traits::DataType< ::srv_cli::ops >
template<>
struct DataType< ::srv_cli::opsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_cli::ops >::value();
  }
  static const char* value(const ::srv_cli::opsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_cli::opsResponse> should match
// service_traits::MD5Sum< ::srv_cli::ops >
template<>
struct MD5Sum< ::srv_cli::opsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_cli::ops >::value();
  }
  static const char* value(const ::srv_cli::opsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_cli::opsResponse> should match
// service_traits::DataType< ::srv_cli::ops >
template<>
struct DataType< ::srv_cli::opsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_cli::ops >::value();
  }
  static const char* value(const ::srv_cli::opsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_CLI_MESSAGE_OPS_H
