// Generated by gencpp from file srv_cli/opsRequest.msg
// DO NOT EDIT!


#ifndef SRV_CLI_MESSAGE_OPSREQUEST_H
#define SRV_CLI_MESSAGE_OPSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_cli
{
template <class ContainerAllocator>
struct opsRequest_
{
  typedef opsRequest_<ContainerAllocator> Type;

  opsRequest_()
    : get_linear_velocity(false)
    , get_radius(false)  {
    }
  opsRequest_(const ContainerAllocator& _alloc)
    : get_linear_velocity(false)
    , get_radius(false)  {
  (void)_alloc;
    }



   typedef uint8_t _get_linear_velocity_type;
  _get_linear_velocity_type get_linear_velocity;

   typedef uint8_t _get_radius_type;
  _get_radius_type get_radius;





  typedef boost::shared_ptr< ::srv_cli::opsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_cli::opsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct opsRequest_

typedef ::srv_cli::opsRequest_<std::allocator<void> > opsRequest;

typedef boost::shared_ptr< ::srv_cli::opsRequest > opsRequestPtr;
typedef boost::shared_ptr< ::srv_cli::opsRequest const> opsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_cli::opsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_cli::opsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_cli::opsRequest_<ContainerAllocator1> & lhs, const ::srv_cli::opsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.get_linear_velocity == rhs.get_linear_velocity &&
    lhs.get_radius == rhs.get_radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_cli::opsRequest_<ContainerAllocator1> & lhs, const ::srv_cli::opsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_cli

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_cli::opsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_cli::opsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_cli::opsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_cli::opsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_cli::opsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_cli::opsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_cli::opsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91e80058a49cbbc5b04d31bbc564e5fd";
  }

  static const char* value(const ::srv_cli::opsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91e80058a49cbbc5ULL;
  static const uint64_t static_value2 = 0xb04d31bbc564e5fdULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_cli::opsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_cli/opsRequest";
  }

  static const char* value(const ::srv_cli::opsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_cli::opsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# client sending some data\n"
"bool get_linear_velocity\n"
"bool get_radius\n"
"\n"
;
  }

  static const char* value(const ::srv_cli::opsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_cli::opsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_linear_velocity);
      stream.next(m.get_radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct opsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_cli::opsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_cli::opsRequest_<ContainerAllocator>& v)
  {
    s << indent << "get_linear_velocity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_linear_velocity);
    s << indent << "get_radius: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.get_radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_CLI_MESSAGE_OPSREQUEST_H
