// Generated by gencpp from file srv_cli/opsResponse.msg
// DO NOT EDIT!


#ifndef SRV_CLI_MESSAGE_OPSRESPONSE_H
#define SRV_CLI_MESSAGE_OPSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_cli
{
template <class ContainerAllocator>
struct opsResponse_
{
  typedef opsResponse_<ContainerAllocator> Type;

  opsResponse_()
    : angular_velocity_value(0.0)  {
    }
  opsResponse_(const ContainerAllocator& _alloc)
    : angular_velocity_value(0.0)  {
  (void)_alloc;
    }



   typedef float _angular_velocity_value_type;
  _angular_velocity_value_type angular_velocity_value;





  typedef boost::shared_ptr< ::srv_cli::opsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_cli::opsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct opsResponse_

typedef ::srv_cli::opsResponse_<std::allocator<void> > opsResponse;

typedef boost::shared_ptr< ::srv_cli::opsResponse > opsResponsePtr;
typedef boost::shared_ptr< ::srv_cli::opsResponse const> opsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_cli::opsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_cli::opsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_cli::opsResponse_<ContainerAllocator1> & lhs, const ::srv_cli::opsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.angular_velocity_value == rhs.angular_velocity_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_cli::opsResponse_<ContainerAllocator1> & lhs, const ::srv_cli::opsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_cli

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_cli::opsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_cli::opsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_cli::opsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_cli::opsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_cli::opsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_cli::opsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_cli::opsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91ce252b066a8019bebcd36427611029";
  }

  static const char* value(const ::srv_cli::opsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91ce252b066a8019ULL;
  static const uint64_t static_value2 = 0xbebcd36427611029ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_cli::opsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_cli/opsResponse";
  }

  static const char* value(const ::srv_cli::opsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_cli::opsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# server sending the result back\n"
"float32 angular_velocity_value\n"
"\n"
"\n"
;
  }

  static const char* value(const ::srv_cli::opsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_cli::opsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular_velocity_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct opsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_cli::opsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_cli::opsResponse_<ContainerAllocator>& v)
  {
    s << indent << "angular_velocity_value: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_CLI_MESSAGE_OPSRESPONSE_H
